### ISSUE TITLE
Helm chart and container image

### ISSUE THREAD

**Issue by steinbrueckri** [FortnoxAB/prometheus-net-discovery#9]
Hi Guys,
has anybody already a helm chart and or a container image in place to use?

Br Richard

**Comment by jonaz** [comment]
We currenty only use this on our standalone prometheus VMs so we have not build an image at this time. Only github precompiled asset for linux-amd64

**Comment by steinbrueckri** [comment]
@jonaz THX for the feedback, I need it for a project as a container in k8s so I will fork the repo and provide a docker build including a helm chart, feel free to close the issue. To anybody how is interested also follow the progress in this repo / branch https://github.com/steinbrueckri/prometheus-net-discovery/tree/container_and_helm

**Comment by sruslanas** [comment]
Helm chart would be really useful

**Comment by steinbrueckri** [comment]
see #10 🎉
